FROM python:3.9-slim

WORKDIR /app

COPY requirements-prod.txt .
RUN pip install --no-cache-dir -r requirements-prod.txt

COPY . .

EXPOSE 8000

# Command to run the API
CMD ["uvicorn", "fast_api.main:app", "--host", "0.0.0.0", "--port", "8000"]